#!/usr/bin/env python3
"""
Generate ortholog mapping files for strains stored in the database.

This script creates 2-way ortholog mapping files between two strains whose
features are stored in the database. The ortholog mappings are retrieved
from the homology_group and feat_homology tables.

Based on generateOrthologFile4StrainsInDB.pl by Prachi Shah (Feb 2011).

Usage:
    python generate_ortholog_file_db_strains.py <strain1> <strain2>
    python generate_ortholog_file_db_strains.py C_albicans_SC5314 C_dubliniensis_CD36

Environment Variables:
    DATABASE_URL: Database connection URL
    DB_SCHEMA: Database schema name
    PROJECT_ACRONYM: Project acronym (CGD or AspGD)
    HTML_ROOT_DIR: Root directory for download files
    LOG_DIR: Directory for log files
"""

import argparse
import logging
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import text

# Add parent directory to path to import cgd modules
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from cgd.db.engine import SessionLocal

# Load environment variables
load_dotenv()

# Configuration from environment
DB_SCHEMA = os.getenv("DB_SCHEMA", "MULTI")
PROJECT_ACRONYM = os.getenv("PROJECT_ACRONYM", "CGD")
HTML_ROOT_DIR = Path(os.getenv("HTML_ROOT_DIR", "/var/www/html"))
LOG_DIR = Path(os.getenv("LOG_DIR", "/var/log/cgd"))
ORTHOLOGY_METHOD = os.getenv("ORTHOLOGY_METHOD", "inparanoid")

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


def get_organism_info(session, strain_abbrev: str) -> dict | None:
    """Get organism information from database."""
    query = text(f"""
        SELECT organism_no, organism_abbrev, organism_name
        FROM {DB_SCHEMA}.organism
        WHERE organism_abbrev = :strain_abbrev
    """)
    result = session.execute(query, {"strain_abbrev": strain_abbrev}).fetchone()
    if not result:
        return None
    return {
        "organism_no": result[0],
        "organism_abbrev": result[1],
        "organism_name": result[2],
    }


def get_seq_source(session, strain_abbrev: str) -> str | None:
    """Get sequence source for a strain."""
    query = text(f"""
        SELECT DISTINCT s.source
        FROM {DB_SCHEMA}.seq s
        JOIN {DB_SCHEMA}.feat_location fl ON s.seq_no = fl.root_seq_no
        JOIN {DB_SCHEMA}.feature f ON fl.feature_no = f.feature_no
        WHERE s.is_seq_current = 'Y'
        AND f.organism_abbrev = :strain_abbrev
        FETCH FIRST 1 ROW ONLY
    """)
    result = session.execute(query, {"strain_abbrev": strain_abbrev}).fetchone()
    return result[0] if result else None


def get_orthologs(session, strain_abbrev1: str, strain_abbrev2: str) -> list[dict]:
    """
    Get ortholog mappings between two strains.

    Returns list of dictionaries with ortholog pair information.
    """
    query = text(f"""
        SELECT DISTINCT
            f1.feature_name, f1.gene_name, f1.dbxref_id,
            f2.dbxref_id, f2.gene_name, f2.feature_name
        FROM {DB_SCHEMA}.feature f1
        JOIN {DB_SCHEMA}.organism o1 ON f1.organism_no = o1.organism_no
        JOIN {DB_SCHEMA}.feat_homology fh1 ON f1.feature_no = fh1.feature_no
        JOIN {DB_SCHEMA}.homology_group hg ON fh1.homology_group_no = hg.homology_group_no
        JOIN {DB_SCHEMA}.feat_homology fh2 ON fh1.homology_group_no = fh2.homology_group_no
        JOIN {DB_SCHEMA}.feature f2 ON fh2.feature_no = f2.feature_no
        JOIN {DB_SCHEMA}.organism o2 ON f2.organism_no = o2.organism_no
        WHERE hg.homology_group_type = 'ortholog'
        AND f1.feature_no != f2.feature_no
        AND o1.organism_abbrev = :strain1
        AND o2.organism_abbrev = :strain2
        ORDER BY f1.feature_name
    """)

    results = []
    for row in session.execute(
        query, {"strain1": strain_abbrev1, "strain2": strain_abbrev2}
    ).fetchall():
        results.append({
            "feat_name1": row[0],
            "gene_name1": row[1] or "",
            "dbxref_id1": row[2],
            "dbxref_id2": row[3],
            "gene_name2": row[4] or "",
            "feat_name2": row[5],
        })

    return results


def generate_file_header(
    strain1: str,
    strain2: str,
    seq_source: str | None,
) -> str:
    """Generate header for the output file."""
    lines = [
        f"# Ortholog mapping: {strain1} to {strain2}",
        f"# Generated by: {PROJECT_ACRONYM}",
        f"# Date: {datetime.now().strftime('%Y-%m-%d')}",
    ]
    if seq_source:
        lines.append(f"# Sequence source: {seq_source}")
    lines.append("#")
    lines.append("# Columns: feature_name1\tgene_name1\tdbxref_id1\tfeature_name2\tgene_name2\tdbxref_id2")
    return "\n".join(lines) + "\n"


def write_ortholog_file(
    orthologs: list[dict],
    output_file: Path,
    strain1: str,
    strain2: str,
    seq_source: str | None,
) -> int:
    """
    Write ortholog mappings to file.

    Returns number of ortholog pairs written.
    """
    with open(output_file, "w") as f:
        f.write(generate_file_header(strain1, strain2, seq_source))

        for orth in orthologs:
            f.write(
                f"{orth['feat_name1']}\t{orth['gene_name1']}\t{orth['dbxref_id1']}\t"
                f"{orth['feat_name2']}\t{orth['gene_name2']}\t{orth['dbxref_id2']}\n"
            )

    return len(orthologs)


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate ortholog mapping files for strains in the database"
    )
    parser.add_argument(
        "strain1",
        help="First strain abbreviation",
    )
    parser.add_argument(
        "strain2",
        help="Second strain abbreviation",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory (default: auto-generated based on strains)",
    )
    parser.add_argument(
        "--method",
        default=ORTHOLOGY_METHOD,
        help=f"Orthology method name for directory (default: {ORTHOLOGY_METHOD})",
    )

    args = parser.parse_args()

    strain1 = args.strain1
    strain2 = args.strain2
    method = args.method.replace(" ", "_")

    # Set up logging
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_file = LOG_DIR / f"ortholog_file_{strain1}_{strain2}.log"
    file_handler = logging.FileHandler(log_file)
    file_handler.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
    logger.addHandler(file_handler)

    logger.info(f"Generating ortholog file for {strain1} to {strain2}")

    try:
        with SessionLocal() as session:
            # Validate strains
            org1 = get_organism_info(session, strain1)
            if not org1:
                logger.error(f"Organism not found: {strain1}")
                return 1

            org2 = get_organism_info(session, strain2)
            if not org2:
                logger.error(f"Organism not found: {strain2}")
                return 1

            logger.info(f"Strain 1: {org1['organism_name']} ({strain1})")
            logger.info(f"Strain 2: {org2['organism_name']} ({strain2})")

            # Get seq_source for header
            seq_source = get_seq_source(session, strain1)

            # Determine output directory and file
            if args.output_dir:
                output_dir = args.output_dir
            else:
                output_dir = (
                    HTML_ROOT_DIR / "download" / "homology" / "orthologs" /
                    f"{strain1}_{strain2}_by_{method}"
                )

            output_dir.mkdir(parents=True, exist_ok=True)
            output_file = output_dir / f"{strain1}_{strain2}_orthologs.txt"

            # Get orthologs
            logger.info("Retrieving ortholog mappings from database...")
            orthologs = get_orthologs(session, strain1, strain2)
            logger.info(f"Found {len(orthologs)} ortholog pairs")

            if not orthologs:
                logger.warning("No orthologs found between these strains")
                return 0

            # Write output file
            count = write_ortholog_file(
                orthologs,
                output_file,
                strain1,
                strain2,
                seq_source,
            )

            logger.info(f"Wrote {count} ortholog pairs to {output_file}")

        return 0

    except Exception as e:
        logger.error(f"Error: {e}")
        return 1

    finally:
        logger.removeHandler(file_handler)
        file_handler.close()


if __name__ == "__main__":
    sys.exit(main())
