#!/usr/bin/env python3
"""
Unit tests for scripts/cron/genespring_format.py

Tests the GeneSpring format file generation functionality.
"""

import gzip
import pytest
from pathlib import Path
from unittest.mock import patch

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent / "scripts"))

from cron.genespring_format import (
    read_gene_association,
    write_genespring_file,
)


class TestReadGeneAssociation:
    """Tests for read_gene_association function."""

    def test_read_basic_gaf(self, temp_file):
        """Test reading basic gene association file."""
        gaf_content = """!gaf-version: 2.2
!Generated by CGD
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:12345\tIDA\t\tF\t\torf19.1|ACT1\tprotein\ttaxon:5476\t20200101\tCGD
CGD\torf19.1\tACT1\t\tGO:0006096\tPMID:12346\tIMP\t\tP\t\torf19.1|ACT1\tprotein\ttaxon:5476\t20200101\tCGD
CGD\torf19.2\tTUB1\t\tGO:0005525\tPMID:12347\tIDA\t\tF\t\torf19.2|TUB1\tprotein\ttaxon:5476\t20200101\tCGD
"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert len(result) == 2
        assert "orf19.1" in result
        assert "orf19.2" in result
        assert "GO:0005524" in result["orf19.1"]
        assert "GO:0006096" in result["orf19.1"]
        assert "GO:0005525" in result["orf19.2"]

    def test_read_gzipped_file(self, temp_dir):
        """Test reading gzipped gene association file."""
        gaf_content = """!gaf-version: 2.2
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:12345\tIDA\t\tF\t\torf19.1|ACT1\tprotein\ttaxon:5476\t20200101\tCGD
"""
        gaf_file = temp_dir / "gene_association.cgd.gz"
        with gzip.open(gaf_file, "wt", encoding="utf-8") as f:
            f.write(gaf_content)

        result = read_gene_association(gaf_file)

        assert len(result) == 1
        assert "orf19.1" in result

    def test_skip_header_lines(self, temp_file):
        """Test that header lines are skipped."""
        gaf_content = """!gaf-version: 2.2
!Generated by CGD
!Date: 2020-01-01
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:12345\tIDA\t\tF\t\torf19.1|ACT1\tprotein\ttaxon:5476\t20200101\tCGD
"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert len(result) == 1

    def test_skip_short_lines(self, temp_file):
        """Test that short lines are skipped."""
        gaf_content = """!header
CGD\torf19.1\tshort
CGD\torf19.2\tTUB1\t\tGO:0005525\tPMID:12347\tIDA\t\tF\t\torf19.2|TUB1\tprotein\ttaxon:5476\t20200101\tCGD
"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert len(result) == 1
        assert "orf19.2" in result

    def test_skip_empty_lines(self, temp_file):
        """Test that empty lines are skipped."""
        gaf_content = """!header

CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:12345\tIDA\t\tF\t\torf19.1|ACT1\tprotein\ttaxon:5476\t20200101\tCGD

"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert len(result) == 1

    def test_multiple_go_ids_same_gene(self, temp_file):
        """Test collecting multiple GO IDs for same gene."""
        gaf_content = """!header
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:1\tIDA\t\tF\t\torf19.1\tprotein\ttaxon:5476\t20200101\tCGD
CGD\torf19.1\tACT1\t\tGO:0006096\tPMID:2\tIMP\t\tP\t\torf19.1\tprotein\ttaxon:5476\t20200101\tCGD
CGD\torf19.1\tACT1\t\tGO:0005737\tPMID:3\tIDA\t\tC\t\torf19.1\tprotein\ttaxon:5476\t20200101\tCGD
"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert len(result) == 1
        assert len(result["orf19.1"]) == 3

    def test_empty_file(self, temp_file):
        """Test reading empty file."""
        gaf_file = temp_file("gene_association.cgd", "")

        result = read_gene_association(gaf_file)

        assert result == {}

    def test_header_only(self, temp_file):
        """Test file with only headers."""
        gaf_content = """!gaf-version: 2.2
!Generated by CGD
"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert result == {}


class TestWriteGenespringFile:
    """Tests for write_genespring_file function."""

    def test_write_basic_file(self, temp_dir):
        """Test writing basic GeneSpring file."""
        gene_goids = {
            "orf19.1": {"GO:0005524", "GO:0006096"},
            "orf19.2": {"GO:0005525"},
        }
        output_file = temp_dir / "genespring.tab"

        count = write_genespring_file(gene_goids, output_file)

        assert count == 2
        assert output_file.exists()

        content = output_file.read_text()
        assert "orf19.1" in content
        assert "orf19.2" in content
        assert "GO:0005524" in content

    def test_write_sorted_genes(self, temp_dir):
        """Test that genes are sorted alphabetically."""
        gene_goids = {
            "zzz": {"GO:0001"},
            "aaa": {"GO:0002"},
            "mmm": {"GO:0003"},
        }
        output_file = temp_dir / "genespring.tab"

        write_genespring_file(gene_goids, output_file)

        content = output_file.read_text()
        lines = content.strip().split("\n")

        assert lines[0].startswith("aaa")
        assert lines[1].startswith("mmm")
        assert lines[2].startswith("zzz")

    def test_write_sorted_goids(self, temp_dir):
        """Test that GO IDs are sorted."""
        gene_goids = {
            "orf19.1": {"GO:0005525", "GO:0001234", "GO:0009999"},
        }
        output_file = temp_dir / "genespring.tab"

        write_genespring_file(gene_goids, output_file)

        content = output_file.read_text()
        line = content.strip()
        goids_part = line.split("\t")[1]

        # GO IDs should be sorted
        goids = goids_part.split("|")
        assert goids == sorted(goids)

    def test_write_empty(self, temp_dir):
        """Test writing with no genes."""
        gene_goids = {}
        output_file = temp_dir / "genespring.tab"

        count = write_genespring_file(gene_goids, output_file)

        assert count == 0
        assert output_file.exists()
        assert output_file.read_text() == ""

    def test_write_skips_empty_goids(self, temp_dir):
        """Test that genes with empty GO IDs are skipped."""
        gene_goids = {
            "orf19.1": {"GO:0005524"},
            "orf19.2": set(),  # Empty set
        }
        output_file = temp_dir / "genespring.tab"

        count = write_genespring_file(gene_goids, output_file)

        assert count == 1
        content = output_file.read_text()
        assert "orf19.1" in content
        assert "orf19.2" not in content


class TestMainFunction:
    """Tests for the main function."""

    def test_main_success(self, temp_dir):
        """Test main with successful execution."""
        from cron.genespring_format import main

        # Create input file
        gaf_content = """!header
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:12345\tIDA\t\tF\t\torf19.1|ACT1\tprotein\ttaxon:5476\t20200101\tCGD
"""
        input_file = temp_dir / "gene_association.cgd"
        input_file.write_text(gaf_content)

        output_file = temp_dir / "output.tab"

        with patch.object(sys, 'argv', [
            'prog',
            '--input', str(input_file),
            '--output', str(output_file)
        ]):
            result = main()

        assert result == 0
        assert output_file.exists()

    def test_main_input_not_found(self, temp_dir):
        """Test main with missing input file."""
        from cron.genespring_format import main

        with patch.object(sys, 'argv', [
            'prog',
            '--input', str(temp_dir / "nonexistent.cgd"),
            '--output', str(temp_dir / "output.tab")
        ]):
            result = main()

        assert result == 1

    def test_main_creates_output_directory(self, temp_dir):
        """Test that output directory is created."""
        from cron.genespring_format import main

        gaf_content = """!header
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:12345\tIDA\t\tF\t\torf19.1|ACT1\tprotein\ttaxon:5476\t20200101\tCGD
"""
        input_file = temp_dir / "gene_association.cgd"
        input_file.write_text(gaf_content)

        output_file = temp_dir / "nested" / "dir" / "output.tab"

        with patch.object(sys, 'argv', [
            'prog',
            '--input', str(input_file),
            '--output', str(output_file)
        ]):
            result = main()

        assert result == 0
        assert output_file.exists()


class TestEdgeCases:
    """Tests for edge cases."""

    def test_gene_with_multiple_aliases(self, temp_file):
        """Test gene with multiple aliases - first one is used."""
        gaf_content = """!header
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:12345\tIDA\t\tF\t\torf19.1|ACT1|ACTIN|CA1234\tprotein\ttaxon:5476\t20200101\tCGD
"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert "orf19.1" in result
        # Other aliases should not be separate keys
        assert "ACT1" not in result
        assert "ACTIN" not in result

    def test_duplicate_go_ids_deduplicated(self, temp_file):
        """Test that duplicate GO IDs are deduplicated."""
        gaf_content = """!header
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:1\tIDA\t\tF\t\torf19.1\tprotein\ttaxon:5476\t20200101\tCGD
CGD\torf19.1\tACT1\t\tGO:0005524\tPMID:2\tIEA\t\tF\t\torf19.1\tprotein\ttaxon:5476\t20200101\tCGD
"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert len(result["orf19.1"]) == 1  # Should be deduplicated

    def test_unicode_in_gaf(self, temp_file):
        """Test handling Unicode characters in GAF file."""
        gaf_content = """!header
CGD\torf19.1\tGène\t\tGO:0005524\tPMID:12345\tIDA\t\tF\t\torf19.1|Gène\tprotein\ttaxon:5476\t20200101\tCGD
"""
        gaf_file = temp_file("gene_association.cgd", gaf_content)

        result = read_gene_association(gaf_file)

        assert "orf19.1" in result

    def test_tab_delimiter_in_output(self, temp_dir):
        """Test that output uses tab delimiter."""
        gene_goids = {
            "orf19.1": {"GO:0005524"},
        }
        output_file = temp_dir / "genespring.tab"

        write_genespring_file(gene_goids, output_file)

        content = output_file.read_text()
        assert "\t" in content
        parts = content.strip().split("\t")
        assert len(parts) == 2
