#!/usr/bin/env python3
"""
Load C. tropicalis gene descriptions generated from C. albicans orthologs.

This script loads gene descriptions (headlines) from the ortholog-based
descriptions file into the feature.headline column.

Usage:
    python load_descriptions.py --descriptions FILE [--dry-run]

Data files needed:
    - ctrop_ortholog_descriptions.tsv (generated by generate_ortholog_descriptions.py)

Environment Variables:
    DATABASE_URL: Database connection URL
    DB_SCHEMA: Database schema name (default: MULTI)
"""
from __future__ import annotations

import argparse
import csv
import logging
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

from dotenv import load_dotenv
from sqlalchemy import text

# Project root directory
PROJECT_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(PROJECT_ROOT / ".env")
sys.path.insert(0, str(PROJECT_ROOT))

from cgd.db.engine import SessionLocal

# Configuration
DB_SCHEMA = os.getenv("DB_SCHEMA", "MULTI")
ADMIN_USER = os.getenv("ADMIN_USER", "cgdadmin").upper()

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def parse_descriptions_file(filepath: Path) -> Dict[str, str]:
    """
    Parse ortholog descriptions TSV file.

    Returns dict of {protein_id: description}
    """
    descriptions = {}

    with open(filepath, 'r') as f:
        reader = csv.DictReader(f, delimiter='\t')
        for row in reader:
            protein_id = row.get('ctrop_protein_id', '').strip()
            description = row.get('generated_description', '').strip()

            if protein_id and description:
                # Truncate description to fit in headline column (240 chars)
                if len(description) > 240:
                    description = description[:237] + "..."
                descriptions[protein_id] = description

    return descriptions


def get_feature_no_by_protein_id(session, protein_id: str) -> Optional[int]:
    """Get feature_no by protein ID."""
    query = text(f"""
        SELECT feature_no
        FROM {DB_SCHEMA}.feature
        WHERE feature_name = :protein_id
    """)
    result = session.execute(query, {"protein_id": protein_id}).first()
    if result:
        return result[0]

    query = text(f"""
        SELECT feature_no
        FROM {DB_SCHEMA}.feature
        WHERE dbxref_id LIKE :pattern
    """)
    result = session.execute(query, {"pattern": f"%{protein_id}%"}).first()
    return result[0] if result else None


def update_feature_headline(
    session,
    feature_no: int,
    headline: str,
    dry_run: bool = False
) -> bool:
    """Update feature headline (description)."""
    if dry_run:
        return True

    update = text(f"""
        UPDATE {DB_SCHEMA}.feature
        SET headline = :headline
        WHERE feature_no = :feature_no
    """)
    session.execute(update, {
        "feature_no": feature_no,
        "headline": headline,
    })
    return True


def load_descriptions(session, descriptions_file: Path, dry_run: bool = False):
    """Load gene descriptions from ortholog-based descriptions file."""
    logger.info(f"Parsing descriptions file: {descriptions_file}")
    descriptions = parse_descriptions_file(descriptions_file)
    logger.info(f"Found {len(descriptions)} descriptions")

    descriptions_loaded = 0
    features_found = 0
    features_not_found = 0

    for protein_id, description in descriptions.items():
        feature_no = get_feature_no_by_protein_id(session, protein_id)

        if not feature_no:
            features_not_found += 1
            continue

        features_found += 1

        updated = update_feature_headline(
            session,
            feature_no=feature_no,
            headline=description,
            dry_run=dry_run
        )
        if updated:
            descriptions_loaded += 1

        if features_found % 500 == 0:
            logger.info(f"Processed {features_found} features...")
            if not dry_run:
                session.commit()

    if not dry_run:
        session.commit()

    logger.info("=" * 60)
    logger.info(f"Features found in database: {features_found}")
    logger.info(f"Features not found: {features_not_found}")
    logger.info(f"Descriptions loaded: {descriptions_loaded}")


def main():
    parser = argparse.ArgumentParser(description="Load C. tropicalis gene descriptions")
    parser.add_argument("--descriptions", required=True, type=Path,
                        help="Ortholog descriptions TSV file")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done")
    args = parser.parse_args()

    logger.info("=" * 60)
    logger.info("Loading C. tropicalis gene descriptions from ortholog data")
    logger.info("=" * 60)

    if args.dry_run:
        logger.info("[DRY RUN MODE]")

    with SessionLocal() as session:
        load_descriptions(session, args.descriptions, args.dry_run)

    logger.info("Done!")


if __name__ == "__main__":
    main()
