#!/usr/bin/env python3
"""Diagnostic: compare +1kb flanking computed two ways for CAGL0M13629G.

  method A (dev / redmine_91_to_95): anchor on FeatLocation min/max
  method B (prod / main):            anchor on subfeature min/max (pooled)

Compares each against the prod and dev strings observed in the UI.
"""
import sys
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
load_dotenv(PROJECT_ROOT / ".env")
sys.path.insert(0, str(PROJECT_ROOT))

from cgd.db.engine import SessionLocal  # noqa: E402
from cgd.models.models import Feature, Seq, FeatLocation, FeatRelationship  # noqa: E402
from sqlalchemy import func  # noqa: E402

COMPLEMENT_MAP = str.maketrans("ACGTacgt", "TGCAtgca")


def rc(s):
    return s.translate(COMPLEMENT_MAP)[::-1]


# Observed UI strings (uppercased, whitespace stripped)
PROD = (
    "GCAAGAAGGCGTAGACATCCTTACCGGCGGCGACAGTGTTAGAGACACCCCCGTTGGAGTTGCTACCAGCGTATGAGAAACCGACGTTGACAGGCTGGTCCAGGAAGATGACCGAGGCGTTAGAGTTCCAGGAGAATGGGTTCTTGACGGGCTTCAATTTTTGTCCGTCGATAGAGGAAGGGCCCAATTCAAAGAATAGACCAGTTAGAGAAGAGCAACCTGGGCCACCGTTCAACCATAGGATGACAGGGTCATTTTTAGGGTCGTTACGGGACTCAAAGAACCAGAAGAAGAAGTGCTTGTCCTCTAGTTCGTTGTCCAAATAACCAGTTAATTGCTTGACGTGAGGGTCGACACCCAGCTTCTTAGGGTTAACAATTTTATTAACTCTCAACTGATGGCCTTCAAGGCCTTCCATCTTCACGACAGCATCCCAGTTCTTCTTCTTCTTGATACCACTTCTTCTTCTGGTACCGAAGCTGATATCATCCAGATGAGCTGGGAAGATGTTCTTCAAAGTGTTCTGAACTGGGGACTTGTTGTAAAAATAGTCCTGAGCTCCCGATAGGGAGAAAGCATCCACTTGGGACAAGACAGCCGCAACACCGGCTAAGTAAGCTAATTTCATTTTGTAGTTTTTTATTTGGTATTGATGGAACCAAAAAAAAAGTAAAGACAGGCAGATATACCAATATATAAGTACTCAATTTATAATCACTTATATTACAGACGAGATAACCCTTTAAATTTCAATAAATTTGACTCAAAAGGATAAGAGAACAATGGACTTTATCACTGCCATGTCACATAAATTATCACTGCCCAAATGTGTCACAATAACCGAAGGACCATACAGAAGGATTATAACAGAACTATTAAACGGGGAATACCAAGTAGAGTGTTCTATAAAATCAAATACAATACGCAACGATTCAGTTTATCTTAACAACTTATCTATACTTCCTTATATATTTTCAAAACTAATACAAAATTTAAAAATATGGTGGCGATGCATTTCAGGAAGAAGTCTAATTTGAGTAATGGCGGCGAGGACGAGCACAGGCTCTCGGATGTCAAGGTGTCTAAGGAGGATGCTGCACGTCTGAAGATCCGTACTGCCTCAGTGAACGATCCTATCTTGGATGCTGTCAACGAAGCTCAACCTTTTGAGCAAGCTGCTGATACTTTCCATGACAACATGAACAGACAGTCCTATTTCTCTACCGACGGTGGTAATGTGCTGCGTGATGTTTTTGGACAGCCTATCACCACTCCTGATATCTCCAACCCTACCAGAGCTAGAGACGAGAGACCACTTGATACCATTAGAAGCTTCGAATATGCTGTCTCTGGTGACCCATCTTGGGCCCAACAGCTAGAGACCGCTACTTACGGTTTCAGGCCAAGACCAGACTTCCCATTGCTAAACCCATACGCTAATAACGCTTCCGCTTCCCAGGCCTACAACGAACAAGCTGTCTACCAACCTCCAGTCCATGAAGTTGGTGAAAAGAAGAAGAAGAAGAGAGGTTTGTTCGGTAGAAAGAAGAAGTCTAAGGATTAAGTATTACTTTATCGATTAGTTCAAGCAAAACCAAAGGAATTTATAATCTTCGCTCAATCTCATTCAACTTATCCATAATAAGATTGTCTTGCTCTTCCATTTTCTGCTCCAACTTGTCCAGCATTACCATCCAATTGTTTTGTTGCTCGGTTAACTTTGACACCCTGGTCTTTAATTCTAAACATATGTTATAGCTGTGCCGTACTTTATTGTCAATGTCGTTATAACTCTCCAATCTTTTCACTAAGGTTGGGAAATGCTCCGTATATTCATCTAGTAATCTGTACATCTTCATCAAATAGGTTAATCTAGTATCATCACCTACAAATTTCGCTTTTAATTCTTCGTGTACTTCTTGATCCTGTTTAGATTGCTTCCCAATTAAACTGTCTTCATATTCCTTTTTTAACTTGCTAAACTTCTCAGAGAAGTCACTCATACAATTCTGATCATCTATTAACAGAATCTTCTTGTATATGCTGTTGATTTCATGAGCCAAAGAGGATACAGAAGAATCGATTCCTCGATTCCCAACTATTTTTTCCAGTCTATCAAGTCTGTTCTCCAATTCGATGAAGTTGTTCATTTTGACAGAATTCAATGAAATATTAATACTCATATCTTCCTTCTCTATATCAGATTTAGTATCAACGATATGCTTTAAAAACTTGTCTCTGTTGTCTATCCTCTCCACATCCAGTACTTTCAGAACCTGGAGAACTTTACCTAGTTCATTGTCATATCCTCCTTTAGTATATTCCTTCTTAAATTTTAAACCATCTAACCTGTCTCTTATCTCTTCTAATTCGTCTTTCTTGGCGTCTTTATAATCGTGCTCTCTCTCAAGCTGTGTCGAAAGTAACTTTCTGGCTTCCAATATCGGCGGTACATGGAAGTGATGCACATCCGCACTGACAGATTCATTATGCTCAATTGTTGATAGTGGAATTTCTTCTAACTCATTGATATCTTCACTTAAGTACTTCTGGTTGATCGATGA"
)
DEV = (
    "TTGACGTGAGGGTCGACACCCAGCTTCTTAGGGTTAACAATTTTATTAACTCTCAACTGATGGCCTTCAAGGCCTTCCATCTTCACGACAGCATCCCAGTTCTTCTTCTTCTTGATACCACTTCTTCTTCTGGTACCGAAGCTGATATCATCCAGATGAGCTGGGAAGATGTTCTTCAAAGTGTTCTGAACTGGGGACTTGTTGTAAAAATAGTCCTGAGCTCCCGATAGGGAGAAAGCATCCACTTGGGACAAGACAGCCGCAACACCGGCTAAGTAAGCTAATTTCATTTTGTAGTTTTTTATTTGGTATTGATGGAACCAAAAAAAAAGTAAAGACAGGCAGATATACCAATATATAAGTACTCAATTTATAATCACTTATATTACAGACGAGATAACCCTTTAAATTTCAATAAATTTGACTCAAAAGGATAAGAGAACAATGGACTTTATCACTGCCATGTCACATAAATTATCACTGCCCAAATGTGTCACAATAACCGAAGGACCATACAGAAGGATTATAACAGAACTATTAAACGGGGAATACCAAGTAGAGTGTTCTATAAAATCAAATACAATACGCAACGATTCAGTTTATCTTAACAACTTATCTATACTTCCTTATATATTTTCAAAACTAATACAAAATTTAAAAATTGAAAATATAATGTAGAAATTATAAGTTTATTCAATAATTTAAATGTAAGATGGTATGTGCAAGGAACGTTGGCTATGATCAAGGCTTTGAAGATTTCTGATACCAAAAACAACACGAACCAGTGTTTGCAGAGGCCAGTGTCTAAATATCACTTCTCGTGTGATGTCCTTGTTTATTAGTGACTTTTCATGGATCAAAAATTTTCTGTCCTTGAATTTGTTAGACAATTCCTCGATCAGCTAACTACCAATATATATTAAGAAGCTATAATAGTTTTGCGCTATATCATCTTTTGTAATAGGATAAGATAACATCATCGAGCAAGAATACAGCAAAGATGGTGGCGATGCATTTCAGGAAGAAGTCTAATTTGAGTAATGGCGGCGAGGACGAGCACAGGCTCTCGGATGTCAAGGTGTCTAAGGAGGATGCTGCACGTCTGAAGATCCGTACTGCCTCAGTGAACGATCCTATCTTGGATGCTGTCAACGAAGCTCAACCTTTTGAGCAAGCTGCTGATACTTTCCATGACAACATGAACAGACAGTCCTATTTCTCTACCGACGGTGGTAATGTGCTGCGTGATGTTTTTGGACAGCCTATCACCACTCCTGATATCTCCAACCCTACCAGAGCTAGAGACGAGAGACCACTTGATACCATTAGAAGCTTCGAATATGCTGTCTCTGGTGACCCATCTTGGGCCCAACAGCTAGAGACCGCTACTTACGGTTTCAGGCCAAGACCAGACTTCCCATTGCTAAACCCATACGCTAATAACGCTTCCGCTTCCCAGGCCTACAACGAACAAGCTGTCTACCAACCTCCAGTCCATGAAGTTGGTGAAAAGAAGAAGAAGAAGAGAGGTTTGTTCGGTAGAAAGAAGAAGTCTAAGGATTAAAGGGTGAAAAAAAATACTGAACTATGATAGCCATTTGGCTGTTTTTGCTAATATTACGAACTTTATTCCTTATACCGAACAAATTTGTTTTTTCTCCCATCCAACTCATTTACAATTTATTTTATTATTCACTTCTTATAAACCCAATCATAACGTTTTTCTCTCAAATTACTAAAGTCTATGCAGGTACATTACTTTCAGATACTTTACAATTTTATATATAACAGGTAGATCACTTTATTTTTCTTTATCCATTTAGTTTATTATATAAACGAAATTATTTCATTTGTATTACTTTATCGATTAGTTCAAGCAAAACCAAAGGAATTTATAATCTTCGCTCAATCTCATTCAACTTATCCATAATAAGATTGTCTTGCTCTTCCATTTTCTGCTCCAACTTGTCCAGCATTACCATCCAATTGTTTTGTTGCTCGGTTAACTTTGACACCCTGGTCTTTAATTCTAAACATATGTTATAGCTGTGCCGTACTTTATTGTCAATGTCGTTATAACTCTCCAATCTTTTCACTAAGGTTGGGAAATGCTCCGTATATTCATCTAGTAATCTGTACATCTTCATCAAATAGGTTAATCTAGTATCATCACCTACAAATTTCGCTTTTAATTCTTCGTGTACTTCTTGATCCTGTTTAGATTGCTTCCCAATTAAACTGTCTTCATATTCCTTTTTTAACTTGCTAAACTTCTCAGAGAAGTCACTCATACAATTCTGATCATCTATTAACAGAATCTTCTTGTATATGCTGTTGATTTCATGAGCCAAAGAGGATACAGAAGAATCGATTCCTCGATTCCCAACTATTTTTTCCAGTCTATCAAGTCTGTTCTCCAATTCGATGAAGTTGTTCATTTTGACAGAATTCAATGAAATATTAATACTCATATCTTCCTTCTCTATATCAGATTTAGTATCAACGATATGCTTTAAAAACTTGTCTCTGTTGTCTATCCTCTCCACATCCAGTACTTTCAGAAC"
)

db = SessionLocal()

feat = (
    db.query(Feature)
    .filter(func.upper(Feature.feature_name) == "CAGL0M13629G")
    .first()
)
print("feature_no=", feat.feature_no, "name=", feat.feature_name, "gene=", feat.gene_name, "type=", feat.feature_type)

loc = (
    db.query(FeatLocation)
    .filter(FeatLocation.feature_no == feat.feature_no, FeatLocation.is_loc_current == "Y")
    .first()
)
print("FeatLocation: start=", loc.start_coord, "stop=", loc.stop_coord,
      "strand=", loc.strand, "root_seq_no=", loc.root_seq_no)

root = db.query(Seq).filter(Seq.seq_no == loc.root_seq_no, Seq.is_seq_current == "Y").first()
chr_seq = root.residues
print("chromosome len=", len(chr_seq))

stored = (
    db.query(Seq)
    .filter(Seq.feature_no == feat.feature_no,
            Seq.seq_type.in_(["genomic", "Genomic DNA"]),
            Seq.is_seq_current == "Y")
    .first()
)
seq = stored.residues
print("stored genomic seq len=", len(seq))


def subfeats(root_seq_no=None):
    q = (
        db.query(Feature.feature_type, FeatLocation.start_coord, FeatLocation.stop_coord)
        .join(FeatRelationship, FeatRelationship.child_feature_no == Feature.feature_no)
        .join(FeatLocation, FeatLocation.feature_no == Feature.feature_no)
        .filter(FeatRelationship.parent_feature_no == feat.feature_no,
                FeatRelationship.rank == 2,
                FeatLocation.is_loc_current == "Y")
    )
    if root_seq_no is not None:
        q = q.filter(FeatLocation.root_seq_no == root_seq_no)
    return q.order_by(FeatLocation.start_coord).all()


sf_pooled = subfeats(None)
sf_scoped = subfeats(loc.root_seq_no)
print("\nsubfeatures POOLED (prod _get_subfeatures, no root filter):")
for r in sf_pooled:
    print("   ", r)
pc = [c for _, a, b in sf_pooled for c in (a, b)]
print("   pooled min/max:", (min(pc), max(pc)) if pc else None)
print("subfeatures SCOPED to root_seq_no:")
for r in sf_scoped:
    print("   ", r)
sc = [c for _, a, b in sf_scoped for c in (a, b)]
print("   scoped min/max:", (min(sc), max(sc)) if sc else None)


def flank(feat_start, feat_stop, strand, fl=1000, fr=1000):
    if strand == "W":
        ls = max(0, feat_start - 1 - fl)
        lf = chr_seq[ls:feat_start - 1]
        rf = chr_seq[feat_stop:feat_stop + fr]
        return lf + seq + rf
    else:
        rs = max(0, feat_start - 1 - fr)
        rf = chr_seq[rs:feat_start - 1]
        lf = chr_seq[feat_stop:feat_stop + fl]
        return rc(lf) + seq + rc(rf)


# Method A: dev (FeatLocation min/max)
a_lo = min(loc.start_coord, loc.stop_coord)
a_hi = max(loc.start_coord, loc.stop_coord)
A = flank(a_lo, a_hi, loc.strand).upper()

# Method B: prod (pooled subfeature min/max)
B = flank(min(pc), max(pc), loc.strand).upper() if pc else None

print("\nstored seq == chr_seq[lo-1:hi] (W) / rc thereof (C)?")
span = chr_seq[a_lo - 1:a_hi]
if loc.strand != "W":
    span = rc(span)
print("   ", span.upper() == seq.upper(), "(span len", len(span), "vs seq len", len(seq), ")")

print("\n== METHOD A (dev / FeatLocation-anchored) ==  len", len(A))
print("   == DEV string? ", A == DEV)
print("   == PROD string?", A == PROD)
print("== METHOD B (prod / subfeature-anchored)  ==  len", len(B) if B else None)
if B:
    print("   == PROD string?", B == PROD)
    print("   == DEV string? ", B == DEV)

print("\nlen(DEV)=", len(DEV), " len(PROD)=", len(PROD), " len(stored)=", len(seq))
db.close()
