#!/usr/bin/env python3
"""
Load transitive orthologs into the database.

Adds C. glabrata features to existing CGOB homology groups based on
the validated additions file generated by validate_transitive_orthologs.py.

Usage:
    python load_transitive_orthologs.py --additions /data/cgob/validation_report_additions.tsv [--dry-run]
"""

import argparse
import logging
import sys
from datetime import datetime

from dotenv import dotenv_values
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Default paths
ENV_FILE = '/home/ec2-user/work/cgd-backend/.env'
CURATOR_USERID = 'ygob_trans'  # Audit trail identifier


def load_additions(filepath: str) -> list[tuple[int, int, str]]:
    """Load additions from TSV file."""
    additions = []
    with open(filepath) as f:
        next(f)  # Skip header
        for line in f:
            parts = line.strip().split('\t')
            if len(parts) >= 3:
                cg_feature_no = int(parts[0])
                hg_no = int(parts[1])
                cg_gene = parts[2]
                additions.append((cg_feature_no, hg_no, cg_gene))
    return additions


def check_existing(conn, feature_no: int, hg_no: int) -> bool:
    """Check if feat_homology record already exists."""
    result = conn.execute(text('''
        SELECT 1 FROM MULTI.feat_homology
        WHERE feature_no = :fno AND homology_group_no = :hg_no
    '''), {'fno': feature_no, 'hg_no': hg_no})
    return result.fetchone() is not None


def get_next_feat_homology_no(conn) -> int:
    """Get the next feat_homology_no from sequence."""
    result = conn.execute(text('''
        SELECT MULTI.feat_homology_seq.NEXTVAL FROM DUAL
    '''))
    return result.scalar()


def insert_feat_homology(conn, feat_homology_no: int, feature_no: int, hg_no: int, curator: str):
    """Insert a new feat_homology record."""
    conn.execute(text('''
        INSERT INTO MULTI.feat_homology (
            feat_homology_no, feature_no, homology_group_no, date_created, created_by
        ) VALUES (
            :fh_no, :fno, :hg_no, SYSDATE, :curator
        )
    '''), {
        'fh_no': feat_homology_no,
        'fno': feature_no,
        'hg_no': hg_no,
        'curator': curator[:12]
    })


def load_orthologs(engine, additions: list, dry_run: bool = True, curator: str = CURATOR_USERID):
    """Load ortholog additions into database."""
    added = 0
    skipped = 0
    errors = []

    with engine.connect() as conn:
        for feature_no, hg_no, cg_gene in additions:
            try:
                # Check if already exists
                if check_existing(conn, feature_no, hg_no):
                    logger.debug(f"Skipping {cg_gene}: already in group {hg_no}")
                    skipped += 1
                    continue

                if dry_run:
                    logger.info(f"[DRY-RUN] Would add {cg_gene} (feature {feature_no}) to group {hg_no}")
                    added += 1
                else:
                    # Get next sequence value
                    fh_no = get_next_feat_homology_no(conn)
                    # Insert record
                    insert_feat_homology(conn, fh_no, feature_no, hg_no, curator)
                    logger.debug(f"Added {cg_gene} (feature {feature_no}) to group {hg_no}")
                    added += 1

            except Exception as e:
                logger.error(f"Error processing {cg_gene}: {e}")
                errors.append((cg_gene, str(e)))

        if not dry_run:
            conn.commit()
            logger.info("Changes committed to database")

    return added, skipped, errors


def verify_additions(engine, additions: list):
    """Verify additions were successful."""
    with engine.connect() as conn:
        verified = 0
        missing = []

        for feature_no, hg_no, cg_gene in additions:
            if check_existing(conn, feature_no, hg_no):
                verified += 1
            else:
                missing.append(cg_gene)

        return verified, missing


def main():
    parser = argparse.ArgumentParser(description='Load transitive orthologs into database')
    parser.add_argument('--additions', required=True, help='Additions TSV file from validation')
    parser.add_argument('--env', default=ENV_FILE, help='Path to .env file')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be done without making changes')
    parser.add_argument('--curator', default=CURATOR_USERID, help='Curator userid for audit trail')
    parser.add_argument('--verify', action='store_true', help='Verify additions after loading')
    args = parser.parse_args()

    # Load environment
    config = dotenv_values(args.env)
    db_url = config.get('DATABASE_URL')
    if not db_url:
        logger.error(f"DATABASE_URL not found in {args.env}")
        sys.exit(1)

    engine = create_engine(db_url)

    # Load additions
    logger.info(f"Loading additions from {args.additions}")
    additions = load_additions(args.additions)
    logger.info(f"Loaded {len(additions)} additions to process")

    if not additions:
        logger.info("No additions to process")
        return

    # Process additions
    if args.dry_run:
        logger.info("=== DRY RUN MODE ===")

    added, skipped, errors = load_orthologs(
        engine,
        additions,
        dry_run=args.dry_run,
        curator=args.curator
    )

    # Summary
    print("\n=== Summary ===")
    print(f"  Records to add: {len(additions)}")
    print(f"  Added: {added}")
    print(f"  Skipped (already exists): {skipped}")
    print(f"  Errors: {len(errors)}")

    if errors:
        print("\nErrors:")
        for gene, error in errors[:10]:
            print(f"  {gene}: {error}")
        if len(errors) > 10:
            print(f"  ... and {len(errors) - 10} more")

    # Verify if requested
    if args.verify and not args.dry_run:
        logger.info("\nVerifying additions...")
        verified, missing = verify_additions(engine, additions)
        print(f"\n=== Verification ===")
        print(f"  Verified: {verified}/{len(additions)}")
        if missing:
            print(f"  Missing: {len(missing)}")
            for gene in missing[:5]:
                print(f"    {gene}")

    if args.dry_run:
        print("\n[DRY RUN] No changes were made. Remove --dry-run to apply changes.")


if __name__ == '__main__':
    main()
